### ISSUE TITLE
Test Link in readme file throws 404 not found

### ISSUE THREAD

**Issue by FedeAmdan** [rolodato/genetics#1]
The link provided in the readme file ( https://github.com/rolodato/genetics/blob/master/src/test/scala/rolodato/genetics/GeneticSpec.scala ) is not accessible.
BTW great work!

**Comment by rolodato** [comment]
Just saw the notification. It's been fixed in b2cbd516af54d87f8a580f7d680370ce029299e2, thanks for reporting!
